<a href="https://colab.research.google.com/github/Optimus0205/Data_Science_Project/blob/main/Data_preprocessing_2_(gurgaon).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('gurgaon_properties.csv')
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
832,3 BHK Flat in Sector 61 Gurgaon,flat,pioneer park,2.10,11666.0,1800.0,Super Built up area 1800(167.23 sq.m.)Carpet a...,3,3,3,not available,"Sector 61 Gurgaon, Gurgaon, Haryana",15.0,South-East,1 to 5 Year Old,"['Sector 55-56 Rapid Metro', 'Hong Kong Bazaar...",3bhk pioneer park sector 61 gurugram\n Additio...,"['3 Wardrobe', '1 Water Purifier', '4 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction3 out of..."
2209,2 BHK Flat in Sector 83 Gurgaon,flat,vatika gurgaon,0.83,6666.0,1245.0,Super Built up area 1245(115.66 sq.m.)Built Up...,2,2,2,pooja room,"Tower F1, Sector 83 Gurgaon, Gurgaon, Haryana",12.0,North,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",Vatika gurgaon 21 is one of the most popular d...,NaN,"['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4.5 out ..."
758,3 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,1.55,9639.0,1608.0,Super Built up area 1608(149.39 sq.m.),3,3,2,pooja room,"Lower Floor, Sector 69 Gurgaon, Gurgaon, Haryana",2.0,East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Check out this 3 bhk apartment for sale in tul...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction4 out of..."
2272,2 BHK Flat in Sector 107 Gurgaon,flat,m3m woodshire,0.88,6442.0,1366.0,Super Built up area 1366(126.91 sq.m.),2,2,3+,not available,"Sector 107 Gurgaon, Gurgaon, Haryana",3.0,East,1 to 5 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...",Corner and airy flat with ample sunlight throu...,"['1 Bed', '5 Fan', '1 Sofa', '10 Light', '3 AC...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Green Area4.5 out of 5', 'Construction5 out ..."
7,3 BHK Flat in Sector 95 Gurgaon,flat,rof ananda,0.38,5899.0,644.0,Carpet area: 644.12 (59.84 sq.m.),3,2,1,pooja room,"203, Sector 95 Gurgaon, Gurgaon, Haryana",2.0,South-East,1 to 5 Year Old,"['Metro', 'Dwarka Expressway', 'Rajeev Chowk',...",Rof ananda is one of gurgaon's most sought aft...,"['5 Fan', '1 Exhaust Fan', '1 Geyser', '8 Ligh...","['Power Back-up', 'Security / Fire Alarm', 'In...","['Environment4 out of 5', 'Lifestyle4.5 out of..."

In [4]:
df.shape

(3623, 20)

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3623 entries, 0 to 3622
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3623 non-null   object
 1   property_type    3623 non-null   object
 2   society          3623 non-null   object
 3   price            3603 non-null   float64
 4   price_per_sqft   3603 non-null   float64
 5   area             3603 non-null   float64
 6   areaWithType     3623 non-null   object
 7   bedRoom          3623 non-null   int64
 8   bathroom         3623 non-null   int64
 9   balcony          3623 non-null   object
 10  additionalRoom   3623 non-null   object
 11  address          3615 non-null   object
 12  floorNum         3603 non-null   float64
 13  facing           2651 non-null   object
 14  agePossession    3621 non-null   object
 15  nearbyLocations  3437 non-null   object
 16  description      3622 non-null   object
 17  furnishDetails   2688 non-null   object
 18  features         3009 non-null   object
 19  rating           3216 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 566.2+ KB

In [7]:
df.isnull().sum()

property_name        0
property_type        0
society              0
price               20
price_per_sqft      20
area                20
areaWithType         0
bedRoom              0
bathroom             0
balcony              0
additionalRoom       0
address              8
floorNum            20
facing             972
agePossession        2
nearbyLocations    186
description          1
furnishDetails     935
features           614
rating             407
dtype: int64

In [8]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sohna,flat,eldeco accolade,0.87,5965.0,1459.0,Super Built up area 1457(135.36 sq.m.)Carpet a...,2,2,3+,study room,"Sohna, Gurgaon, Haryana",10.0,NaN,1 to 5 Year Old,"['Global City Centre', 'Sohna Road', 'Damdama ...",Residential apartment for sell.The property ha...,[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction4.5 out ..."
1,4 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,2.00,9583.0,2087.0,Super Built up area 2087(193.89 sq.m.),4,4,2,not available,"002, Sector 69 Gurgaon, Gurgaon, Haryana",0.0,South-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Ground floor with extended balcony this 4 bhk ...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4 out of..."
2,3 BHK Flat in Sector 47 Gurgaon,flat,unitech uniworld gardens,2.40,11505.0,2086.0,Super Built up area 2086(193.8 sq.m.),3,3,3+,servant room,"Sector 47 Gurgaon, Gurgaon, Haryana",10.0,NaN,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'Standard chartered ATM...","3bhk + sq, 2086 sq feet\nSemi-Furnished \nNewl...","['3 Wardrobe', '6 Fan', '3 Geyser', '15 Light'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4 out of 5', 'Construction4 out of..."
3,3 BHK Flat in Sector 83 Gurgaon,flat,emaar palm gardens,1.75,9210.0,1900.0,Super Built up area 1900(176.52 sq.m.)Built Up...,3,3,3,servant room,"403, Sector 83 Gurgaon, Gurgaon, Haryana",6.0,East,1 to 5 Year Old,"[""V'Lante Mall"", 'NH 48 Gurugram', 'iGrow Mont...",This 3 bhk flat is located in emaar palm garde...,"['3 Wardrobe', '8 Fan', '1 Exhaust Fan', '1 Di...","['Water purifier', 'Centrally Air Conditioned'...","['Green Area5 out of 5', 'Construction4 out of..."
4,2 BHK Flat in Sector 82 Gurgaon,flat,vatika iris floors,0.63,5590.0,1127.0,Super Built up area 1134(105.35 sq.m.),2,2,3+,study room,"Sector 82 Gurgaon, Gurgaon, Haryana",2.0,East,1 to 5 Year Old,"['Vatika Town Square-INXT', 'NH 48, Sector 78,...",This property is very good becouse of itsattre...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [9]:
df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip()

0                                                   Sohna
1                                               Sector 69
2                                               Sector 47
3                                               Sector 83
4                                               Sector 82
5                                           Rajendra Park
6                                         Sector-33 Sohna
7                                               Sector 95
8                                               Sector 65
9                                               Sector 31
10                                              Sector 95
11                                            DLF Phase 2
12                                              Sector 90
13                                              Sector 66
14                                              Sector 45
15                                              Sector 85
16                                             Sector 108
17                                              Sector 69
18                                              Sector 90
19                                              Sector 56
20                                              Sector 85
21                                              Sector 83
22                                              Sector 65
23                                        Sector-33 Sohna
24                                             Sector 67A
25                                              Sector 69
26                                              Sector 46
27                                              Sector 92
28                                              Sector 72
29                                              Sector 84
30                                              Sector 95
31                                             Sector 107
32                                              Sector 93
33                                             Sector 112
34                                             Sector 37C
35                                              Sector 85
36                                             Sector 104
37                                             Sector 67A
38                                              Sector 65
39                                              Sector 70
40                                              Sector 84
41                                        Uppals Southend
42                                             Sector 70A
43                                              Sector 50
44                                              Sector 15
45                                              Sector 81
46                                              Sector 90
47                                              Sector 92
48                                              Sector 55
49                                              Sector 79
50                                              Sector 89
51                                             Sector 113
52                                        Sector-33 Sohna
53                                             Sector 82A
54                                            DLF Phase 4
55                                              Sector 84
56                                             Sector 37C
57                                         Sheetla Colony
58                                              Sector 85
59                                                  Sohna
60                                              Sector 70
61                                              Sector 67
62                                             Sector 70A
63                                              Sector 26
64                                    Udyog Vihar Phase 1
65                                              Sector 76
66                                    Sushant Lok Phase 1
67                                              Sector 14
68                                              Sector 84
69                                             Sector 107
70                                              Sector 45
71                                              Sector 85
72                                             Sector 107
73                                               Sector 7
74                                              Sector 89
75                                            DLF Phase 1
76                                              Sector 95
77                                              Sector 70
78                                            DLF Phase 5
79                                              Sector 78
80                                         Greenwood City
81                                              Sector 56
82                                             Sector 37D
83                                              Sector 67
84                                      Dwarka Expressway
85                                              Sector 81
86                                    Sushant Lok Phase 1
87                                             Sector 70A
88                                              Sector 82
89                                              Sector 65
90                                        Sector-33 Sohna
91                                             Sector 70A
92                                              Sector 65
93                                        Sector-33 Sohna
94                                              Sector 50
95                                              Sector 89
96                                              Sector 85
97                                              Sector 79
98                                              Sector 57
99                                        Dayanand Colony
100                                           Rajiv Chowk
101                                            Sector 70A
102                                          Mahavir pura
103                                            Sector 112
104                                            Sector 99A
105                                             Sector 70
106                                           DLF Phase 3
107                                            Sector 109
108                                             Sector 56
109                                             Sultanpur
110                                            Sector 108
111                                             Sector 30
112                                             Sector 92
113                                       Nirvana Country
114                                             Sector 73
115                                             Sector 81
116                                            Sector 99A
117                                             Sector 82
118                                             Sector 69
119                                             Sector 92
120                                   Ansal's Palam Vihar
121                                            Sector 99A
122                                            Sector 104
123                                             Sector 92
124                           A Block Sushant Lok Phase 1
125                                             Sector 81
126                                   Sushant Lok Phase 1
127                                             Sector 81
128                                             Sector 67
129                                       Sector-33 Sohna
130                                             Sector 79
131                                            Sector 102
132                                         Rajendra Park
133                                             Sector 46
134                                             Sector 40
135                                             Sector 39
136                                             Sector 47
137                                            Sector 109
138                                            Sector 109
139                                             Sector 92
140                                        Greenwood City
141                                             Sector 53
142                                            Sector 12A
143                                                 Sohna
144                                         Rajendra Park
145                                             Sector 69
146                                           DLF Phase 1
147                                       Sector 36 Sohna
148                                             Sector 77
149                                             Sector 92
150                                             Sector 85
151                                       Saraswati Vihar
152                                             Sector 76
153                                             Sector 54
154                                            Sector 37D
155                                              Sector 9
156                                            Sector 104
157                                            Sector 37D
158                                            Sector 113
159                                             Sector 79
160                                             Sector 14
161                                             Sector 81
162                                             Sector 83
163                                            Sector 37C
164                                             Sector 14
165                                            Sector 113
166                                            Sector 88A
167                                            Sector 37D
168                                             Sector 82
169                                            Sector 108
170                                           Malibu Town
171                                             Sector 95
172                                             Sector 65
173                                             Sector 72
174                                       Mayfield Garden
175                                            Sector 106
176                                            Sector 105
177                                 Palam Vihar Extension
178                                             Sector 85
179                                        Devilal Colony
180                                            Sector 107
181                                             Sector 95
182                                             Sector 84
183                                             Sector 85
184                                             Sector 86
185                                             Sector 85
186                                             Sector 59
187                                             Sector 89
188                                             Sector 85
189                                         Shivaji Nagar
190                                       Mianwali Colony
191                                             Sector 89
192                                            Sector 102
193                                  Sector 1 Imt Manesar
194                                   Sushant Lok Phase 1
195                                            Sector 37D
196                                            Sector 102
197                           C Block Sushant Lok Phase 1
198                                             Sector 62
199                                                 Sohna
200                                            Sector 106
201                                            Sector 104
202                                          Laxman Vihar
203                                             Sector 95
204                                             Sector 79
205                                             Sector 81
206                                                 Sohna
207                                             Sector 67
208                                             Sector 85
209                                             Sector 69
210                                   Sushant Lok Phase 3
211                                             Sector 61
212                                            Sector 23A
213                                             Sector 56
214                                            Sector 102
215                                             Sector 36
216                                             Sector 92
217                                           Palam Vihar
218                                             Sector 14
219                                             Sector 68
220                                            New Colony
221                                            Sector 63A
222                                           DLF Phase 3
223                                                 Sohna
224                                            Sector 107
225                                       Nirvana Country
226                                              Sector 9
227                                        Tekchand Nagar
228                                             Sector 92
229                                          Laxman Vihar
230                                             Sector 48
231                                            Chakkarpur
232                                             Sector 85
233                                            Sector 113
234                                             Sector 39
235                                            Sector 99A
236                                             Sector 84
237                                   Sushant Lok Phase 1
238                                   Sushant Lok Phase 1
239                                             Sector 82
240                                             Sector 86
241                                             Sector 85
242                                             New Basti
243                                           DLF Phase 1
244                                            Sector 102
245                                             Sector 86
246                                             Sector 38
247                                            Sector 37D
248                                             Sector 69
249                                             Sector 66
250                                            Sector 37D
251                                             Sector 81
252                                             Sector 79
253                                             Sector 90
254                                             Sector 66
255                                           Palam Vihar
256                                             Sector 86
257                                            Sohna Road
258                                             Sector 54
259                                       Nirvana Country
260                                             Sector 90
261                                           Palam Vihar
262                                             Sector 49
263                                       New Palam Vihar
264                                             Sector 81
265                                       Nirvana Country
266                                            Sector 104
267                                             Sector 65
268                                             Sector 86
269                                            Sector 108
270                                             Sector 86
271                                             Sector 92
272                                       New Palam Vihar
273                                             Sector 48
274                                             Sector 67
275                                            Sector 82A
276                                             Sector 56
277                                           IMT Manesar
278                                             Sector 91
279                                            Sector 104
280                                             Sector 65
281                                            Sector 109
282                                             Sector 85
283                                             Sector 85
284                                             Sector 82
285                                             Sector 84
286                                            Sector 102
287                                             Sector 54
288                                             Sector 89
289                                  Laxman Vihar Phase 2
290                                            Sector 103
291                                             Sector 56
292                                           DLF Phase 1
293                                             Sector 83
294                                                 Sohna
295                                             Sector 85
296                                             Sector 74
297                                             Sector 79
298                                             Sector 92
299                                            Sector 109
300                                   Sushant Lok Phase 3
301                                             Sector 72
302                                          Gandhi Nagar
303                                             Sector 70
304                                             Sector 67
305                                            Sector 37D
306                                            Sector 102
307                                            Sector 104
308                                             Sector 61
309                                             Sector 89
310                                             Sector 83
311                                             Sector 85
312                                            Sector 109
313                                             Sector 3A
314                                             Sector 61
315                                           Palam Vihar
316                                              Sector 7
317                                             Sector 60
318                                            Sector 109
319                                             Sector 83
320                                            Sector 109
321                                             Sector 69
322                                             Sector 48
323                                            Sector 109
324                                            Sector 108
325                                       Mianwali Colony
326                                           DLF Phase 2
327                                             Sector 53
328                                             Sector 69
329                                         Garhi Harsaru
330                                            Sector 109
331                                             Sector 83
332                                            Sector 104
333                                             Sector 66
334                                             Sector 86
335                                             Sector 33
336                                              Sector 6
337                                              Sector 1
338                                             Sector 81
339                                           Palam Vihar
340                                                 Sohna
341                                             Sector 65
342                                             Sector 95
343                                             Sector 33

In [10]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sohna,flat,eldeco accolade,Sohna,0.87,5965.0,1459.0,Super Built up area 1457(135.36 sq.m.)Carpet a...,2,2,3+,study room,"Sohna, Gurgaon, Haryana",10.0,NaN,1 to 5 Year Old,"['Global City Centre', 'Sohna Road', 'Damdama ...",Residential apartment for sell.The property ha...,[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction4.5 out ..."
1,4 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,Sector 69,2.00,9583.0,2087.0,Super Built up area 2087(193.89 sq.m.),4,4,2,not available,"002, Sector 69 Gurgaon, Gurgaon, Haryana",0.0,South-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Ground floor with extended balcony this 4 bhk ...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4 out of..."
2,3 BHK Flat in Sector 47 Gurgaon,flat,unitech uniworld gardens,Sector 47,2.40,11505.0,2086.0,Super Built up area 2086(193.8 sq.m.),3,3,3+,servant room,"Sector 47 Gurgaon, Gurgaon, Haryana",10.0,NaN,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'Standard chartered ATM...","3bhk + sq, 2086 sq feet\nSemi-Furnished \nNewl...","['3 Wardrobe', '6 Fan', '3 Geyser', '15 Light'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4 out of 5', 'Construction4 out of..."
3,3 BHK Flat in Sector 83 Gurgaon,flat,emaar palm gardens,Sector 83,1.75,9210.0,1900.0,Super Built up area 1900(176.52 sq.m.)Built Up...,3,3,3,servant room,"403, Sector 83 Gurgaon, Gurgaon, Haryana",6.0,East,1 to 5 Year Old,"[""V'Lante Mall"", 'NH 48 Gurugram', 'iGrow Mont...",This 3 bhk flat is located in emaar palm garde...,"['3 Wardrobe', '8 Fan', '1 Exhaust Fan', '1 Di...","['Water purifier', 'Centrally Air Conditioned'...","['Green Area5 out of 5', 'Construction4 out of..."
4,2 BHK Flat in Sector 82 Gurgaon,flat,vatika iris floors,Sector 82,0.63,5590.0,1127.0,Super Built up area 1134(105.35 sq.m.),2,2,3+,study room,"Sector 82 Gurgaon, Gurgaon, Haryana",2.0,East,1 to 5 Year Old,"['Vatika Town Square-INXT', 'NH 48, Sector 78,...",This property is very good becouse of itsattre...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [11]:
df['sector'] = df['sector'].str.lower()
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sohna,flat,eldeco accolade,sohna,0.87,5965.0,1459.0,Super Built up area 1457(135.36 sq.m.)Carpet a...,2,2,3+,study room,"Sohna, Gurgaon, Haryana",10.0,NaN,1 to 5 Year Old,"['Global City Centre', 'Sohna Road', 'Damdama ...",Residential apartment for sell.The property ha...,[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction4.5 out ..."
1,4 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,sector 69,2.00,9583.0,2087.0,Super Built up area 2087(193.89 sq.m.),4,4,2,not available,"002, Sector 69 Gurgaon, Gurgaon, Haryana",0.0,South-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Ground floor with extended balcony this 4 bhk ...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4 out of..."
2,3 BHK Flat in Sector 47 Gurgaon,flat,unitech uniworld gardens,sector 47,2.40,11505.0,2086.0,Super Built up area 2086(193.8 sq.m.),3,3,3+,servant room,"Sector 47 Gurgaon, Gurgaon, Haryana",10.0,NaN,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'Standard chartered ATM...","3bhk + sq, 2086 sq feet\nSemi-Furnished \nNewl...","['3 Wardrobe', '6 Fan', '3 Geyser', '15 Light'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4 out of 5', 'Construction4 out of..."
3,3 BHK Flat in Sector 83 Gurgaon,flat,emaar palm gardens,sector 83,1.75,9210.0,1900.0,Super Built up area 1900(176.52 sq.m.)Built Up...,3,3,3,servant room,"403, Sector 83 Gurgaon, Gurgaon, Haryana",6.0,East,1 to 5 Year Old,"[""V'Lante Mall"", 'NH 48 Gurugram', 'iGrow Mont...",This 3 bhk flat is located in emaar palm garde...,"['3 Wardrobe', '8 Fan', '1 Exhaust Fan', '1 Di...","['Water purifier', 'Centrally Air Conditioned'...","['Green Area5 out of 5', 'Construction4 out of..."
4,2 BHK Flat in Sector 82 Gurgaon,flat,vatika iris floors,sector 82,0.63,5590.0,1127.0,Super Built up area 1134(105.35 sq.m.),2,2,3+,study room,"Sector 82 Gurgaon, Gurgaon, Haryana",2.0,East,1 to 5 Year Old,"['Vatika Town Square-INXT', 'NH 48, Sector 78,...",This property is very good becouse of itsattre...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [12]:
df['sector'].value_counts()

sector
sohna                                                        131
sector 102                                                   111
sector 85                                                    107
sector 69                                                     91
sector 109                                                    85
sector 65                                                     85
sector 90                                                     84
sector 81                                                     84
sector 92                                                     82
sector 79                                                     71
sector 83                                                     68
sector 86                                                     60
sector 37d                                                    60
sector 107                                                    59
sector 104                                                    55
sector 108                                                    55
sector 48                                                     54
sector 56                                                     53
sector 70a                                                    53
nirvana country                                               53
sector 84                                                     50
sector 89                                                     48
sector 67                                                     48
sector 70                                                     47
palam vihar                                                   46
sector 66                                                     46
sector-33 sohna                                               45
sector 95                                                     43
dlf phase 2                                                   43
sector 37c                                                    43
dlf phase 1                                                   43
sector 113                                                    41
sector 82                                                     39
sector 103                                                    38
sector 106                                                    36
sector 49                                                     34
sector 61                                                     33
sushant lok phase 1                                           31
sector 72                                                     29
sector 77                                                     27
laxman vihar                                                  25
sector 99a                                                    25
sector 54                                                     25
sector 68                                                     24
sector 71                                                     24
dlf phase 4                                                   23
sector 112                                                    23
sector 111                                                    21
sector 33                                                     21
dlf phase 3                                                   21
sector 67a                                                    20
sector 88a                                                    18
sector 82a                                                    18
sector 62                                                     17
sector 91                                                     17
sector 63a                                                    17
sector 74                                                     17
sector 22                                                     15
sector 60                                                     15
sector 14                                                     15
sushant lok phase 3                                           15
sector 63                                                     15
gwal pahari                                                   14
sector 110                                                    14
sector 1 imt manesar                                          14
laxman vihar phase 2                                          13
dlf phase 5                                                   13
rajendra park                                                 13
sector 46                                                     13
sector 39                                                     12
sector 31                                                     12
sector 53                                                     12
sector 38                                                     12
sector 93                                                     12
uppals southend                                               12
sector 50                                                     12
sector 52                                                     12
sector 78                                                     11
sector 3                                                      11
sector 36a                                                    11
sector 99                                                     11
sohna road                                                    11
sector 76                                                     11
ashok vihar phase 3 extension                                 10
sector 47                                                     10
sector 7                                                      10
sector 4                                                       9
south city 1                                                   8
c block sushant lok phase 1                                    8
malibu town                                                    8
sector 57                                                      8
ashok vihar phase 2                                            8
sector 95a                                                     8
sector 89 a                                                    8
sector 55                                                      8
sector 10a                                                     7
sector 58                                                      7
mianwali colony                                                7
sector 59                                                      7
palam vihar extension                                          7
new colony                                                     7
sector 26                                                      7
sector 1a imt manesar                                          7
sector 11                                                      7
surat nagar 1                                                  7
sector 51                                                      7
sector 9a                                                      7
sector 43                                                      7
sector 40                                                      7
mehrauli  road                                                 6
sector 5                                                       6
rajiv nagar                                                    6
jacobpura                                                      6
dwarka expressway                                              6
sector 36 sohna                                                6
jyoti park                                                     6
sector 1                                                       6
greenwood city                                                 5
arjun nagar                                                    5
chakkarpur                                                     5
subhash nagar                                                  5
manesar                                                        5
sushant lok phase 2                                            5
sector 28                                                      5
sector 23a                                                     5
sector 30                                                      5
saraswati vihar                                                5
ansal plaza                                                    5
sector 3a                                                      4
garhi harsaru                                                  4
new palam vihar                                                4
sector 36                                                      4
sector 6                                                       4
sector 9                                                       4
madanpuri                                                      4
surya vihar                                                    4
sector 12a                                                     4
sector 45                                                      4
devilal colony                                                 4
shivaji nagar                                                  4
suncity                                                        4
sector 2                                                       4
baldev nagar                                                   4
shivpuri                                                       4
ashok vihar                                                    4
bhim nagar                                                     4
sector 17                                                      4
vishnu garden                                                  4
ravi nagar                                                     4
krishna colony                                                 4
patel nagar                                                    3
maruti kunj                                                    3
sector 27                                                      3
prem nagar                                                     3
sector 110 a                                                   3
sector 88b                                                     3
sector 8                                                       3
a block sushant lok phase 1                                    3
dayanand colony                                                3
sector 105                                                     3
sector 73                                                      3
sector 17b                                                     3
imt manesar                                                    3
gandhi nagar                                                   3
sector 15                                                      3
mg road                                                        3
sector 12                                                      3
sector 80                                                      3
bhondsi                                                        3
sector 17a                                                     3
laxmi garden                                                   3
shakti nagar                                                   3
sector 23                                                      3
b block sushant lok phase 1                                    3
new palam vihar phase 2                                        2
lajpat nagar                                                   2
sector 15 part 1                                               2
samaspur                                                       2
hira nagar                                                     2
shankar vihar                                                  2
sector-11 sohna                                                2
farukhnagar                                                    2
nars                                                           2
mohan nagar                                                    2
surat nagar                                                    2
surat nagar phase 2                                            2
iffco chowk                                                    2
block a surya vihar                                            2
, delhi ncr                                                    2
bissar                                                         2
pratap nagar                                                   2
sector 15 part 2                                               2
adarsh nagar                                                   2
rosewood                                                       2
ambience island                                                2
bhawani enclave                                                2
sheetla colony                                                 2
new basti                                                      2
west rajiv nagar                                               2
sector 32                                                      2
new palam vihar phase 1                                        2
mayfield garden                                                2
rajiv chowk                                                    2
acharya puri                                                   2
faridabad road                                                 2
sushant lok                                                    2
golf course road                                               2
manohar nagar                                                  2
dharam colony                                                  2
sohna  road                                                    2
daulatabad                                                     2
sector 41                                                      2
sispal vihar                                                   2
ashok vihar phase 3                                            1
tekchand nagar                                                 1
near sector 1 market                                           1
new                                                            1
carterpuri village                                             1
lucknow                                                        1
jacobpura near sadar bazar                                     1
g block dlf city phase 1                                       1
dhankot                                                        1
om nagar                                                       1
jat colony,fazilpur/taj nagar road                             1
sultanpur                                                      1
sec 3 bhim vihar part 1 bhimgher kheri                         1
civil l                                                        1
ats marigold                                                   1
ansal's palam vihar                                            1
mahavir pura                                                   1
new jyoti park                                                 1
old delhi road, opp sector-14                                  1
block h ashok vihar phase iii extension                        1
block g sector-57                                              1
near euro                                                      1
hno 13 sagar enclave sura                                      1
golf course ext road                                           1
udyog vihar phase 1                                            1
near pataudi chowk                                             1
ashok vihar phase i                                            1
anand garden, sector-105                                       1
sector 24                                                      1
near nand hospital                                             1
pataudi road                                                   1
sector-2 sohna                                                 1
sector 9b                                                      1
begampur khatola                                               1
sai kunj                                                       1
bhimgarh kheri phase 3                                         1
sector 17c                                                     1
heritage city                                                  1
nirvana country pocket h                                       1
sector-5 sohna                                                 1
sector 21a faridabad                                           1
sector 37b                                                     1
saraswati enclave                                              1
ram nagar                                                      1
v block dlf phase 3                                            1
south city                                                     1
sector 37a                                                     1
cyber city                                                     1
b1 block sector 57                                             1
park view                                                      1
sector 21                                                      1
hsiidc plot sector 1 imt manesar                               1
urban estate, sector 5                                         1
damdma                                                         1
kheri                                                          1
part 3 sector 5                                                1
new colony, sector 7                                           1
huda saraswati vihar                                           1
laxman vihar, railway road,                                    1
devi lal colony gali no 12 gurgaon nr omkar public school      1
kanahi                                                         1
shivji park colony                                             1
laxmna vihar, phase 2                                          1
sadar bazar                                                    1
vir nagar                                                      1
garauli kalan                                                  1
valley view estate                                             1
sector-5 sheetla colony                                        1
mahalaxmi garden, rajendra place                               1
sector 13                                                      1
sector 42                                                      1
sector 5 chowk                                                 1
gopal nagar, garhi ghasita, sonipat                            1
rajiv colony                                                   1
bhora kalan                                                    1
alipur                                                         1
naharpur rupa                                                  1
sector-7 hous                                                  1
shanti nagar                                                   1
ravi nager basai road                                          1
rattan garden                                                  1
near khandsa road                                              1
khandsa                                                        1
Name: count, dtype: int64

###Replacing the sector values

In [13]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [14]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [15]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [16]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [17]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [18]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [19]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [20]:
# Removing the societies which are less than 3
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [21]:
df['sector'].value_counts()

sector
sohna road                    131
sector 102                    111
sector 85                     107
sector 69                      91
sector 109                     85
sector 65                      85
sector 90                      84
sector 81                      84
sector 92                      82
sector 79                      71
sector 83                      68
sector 50                      65
sector 104                     62
sector 37d                     60
sector 86                      60
sector 107                     59
sector 108                     55
sector 48                      54
sector 70a                     53
sector 56                      53
sector 43                      51
sector 84                      50
sector 26                      50
sector 2                       50
sector 89                      48
sector 67                      48
sector 70                      47
sector 66                      46
sector 49                      46
sector-33 sohna road           45
sector 28                      44
sector 95                      43
sector 25                      43
sector 37c                     43
sector 113                     41
sector 82                      39
sector 7                       39
sector 103                     38
sector 106                     36
sector 4                       34
sector 61                      33
sector 72                      29
sector 54                      29
sector 77                      27
sector 12                      25
sector 99a                     25
sector 71                      24
sector 68                      24
sector 57                      23
sector 112                     23
sector 24                      22
sector 33                      21
sector 111                     21
sector 14                      21
sector 105                     20
sector 67a                     20
sector 11                      20
sector 88a                     18
sector 47                      18
sector 82a                     18
sector 63a                     17
sector 74                      17
sector 62                      17
sector 91                      17
sector 60                      15
sector 3                       15
sector 22                      15
gwal pahari                    15
sector 63                      15
sector 110                     14
sector 1 manesar               14
sector 4 phase 2               13
sector 55                      13
sector 46                      13
sector 93                      12
sector 52                      12
sector 38                      12
sector 53                      12
sector 39                      12
sector 31                      12
sector 9                       12
sector 6                       11
sohna road road                11
sector 78                      11
sector 76                      11
sector 36a                     11
sector 99                      11
sector 3 phase 3 extension     10
sector 41                      10
sector 13                      10
sector 45                       9
sector 89 a                     8
c block sector 43               8
sector 17                       8
sector 95a                      8
sector 23                       8
sector 3 phase 2                8
sector 8                        8
manesar                         8
sector 58                       7
sector 1a manesar               7
sector 10a                      7
sector 9a                       7
sector 51                       7
sector 2 extension              7
sector 40                       7
sector 59                       7
sector 5                        6
dwarka expressway               6
sector 1                        6
sector 36 sohna road            6
sector 30                       5
sector 23a                      5
sector 21                       5
sector 3a                       4
new sector 2                    4
sector 36                       4
sector 12a                      4
a block sector 43               3
sector 73                       3
sector 15                       3
sector 17b                      3
maruti kunj                     3
patel nagar                     3
sector 17a                      3
sector 27                       3
sector 110 a                    3
sector 88b                      3
sector 80                       3
b block sector 43               3
Name: count, dtype: int64

In [22]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [23]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [24]:
df[df['sector'] == 'new']

Empty DataFrame
Columns: [property_name, property_type, society, sector, price, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [25]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [26]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
263,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
272,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
390,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
1897,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [27]:
df.loc[[263,272,390,1897],'sector'] = 'sector 110'

In [28]:
df.shape

(3472, 21)

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sohna,flat,eldeco accolade,sohna road,0.87,5965.0,1459.0,Super Built up area 1457(135.36 sq.m.)Carpet a...,2,2,3+,study room,"Sohna, Gurgaon, Haryana",10.0,NaN,1 to 5 Year Old,"['Global City Centre', 'Sohna Road', 'Damdama ...",Residential apartment for sell.The property ha...,[],"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction4.5 out ..."
1,4 BHK Flat in Sector 69 Gurgaon,flat,tulip violet,sector 69,2.00,9583.0,2087.0,Super Built up area 2087(193.89 sq.m.),4,4,2,not available,"002, Sector 69 Gurgaon, Gurgaon, Haryana",0.0,South-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Ground floor with extended balcony this 4 bhk ...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4 out of..."
2,3 BHK Flat in Sector 47 Gurgaon,flat,unitech uniworld gardens,sector 47,2.40,11505.0,2086.0,Super Built up area 2086(193.8 sq.m.),3,3,3+,servant room,"Sector 47 Gurgaon, Gurgaon, Haryana",10.0,NaN,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'Standard chartered ATM...","3bhk + sq, 2086 sq feet\nSemi-Furnished \nNewl...","['3 Wardrobe', '6 Fan', '3 Geyser', '15 Light'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4 out of 5', 'Construction4 out of..."
3,3 BHK Flat in Sector 83 Gurgaon,flat,emaar palm gardens,sector 83,1.75,9210.0,1900.0,Super Built up area 1900(176.52 sq.m.)Built Up...,3,3,3,servant room,"403, Sector 83 Gurgaon, Gurgaon, Haryana",6.0,East,1 to 5 Year Old,"[""V'Lante Mall"", 'NH 48 Gurugram', 'iGrow Mont...",This 3 bhk flat is located in emaar palm garde...,"['3 Wardrobe', '8 Fan', '1 Exhaust Fan', '1 Di...","['Water purifier', 'Centrally Air Conditioned'...","['Green Area5 out of 5', 'Construction4 out of..."
4,2 BHK Flat in Sector 82 Gurgaon,flat,vatika iris floors,sector 82,0.63,5590.0,1127.0,Super Built up area 1134(105.35 sq.m.),2,2,3+,study room,"Sector 82 Gurgaon, Gurgaon, Haryana",2.0,East,1 to 5 Year Old,"['Vatika Town Square-INXT', 'NH 48, Sector 78,...",This property is very good becouse of itsattre...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [31]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [32]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
454,house,independent,sohna road,1.50,14245.0,1053.0,Plot area 117(97.83 sq.m.),2,3,2,"pooja room,study room",1.0,North,0 to 1 Year Old,NaN,"['6 Fan', '3 Geyser', '40 Light', '3 AC', '1 C...","['Private Garden / Terrace', 'High Ceiling Hei..."
475,flat,bptp terra,sector 37d,1.55,7074.0,2191.0,Super Built up area 2191(203.55 sq.m.)Built Up...,4,3,3+,others,19.0,North-East,1 to 5 Year Old,"['Airia Mall', 'Dwarka Expressway', 'Golf Cour...","['2 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
1249,flat,signature the roselia,sector 95,0.41,6194.0,662.0,Built Up area: 670 (62.25 sq.m.)Carpet area: 5...,2,2,2,study room,12.0,North,0 to 1 Year Old,"['Newtown Square Mall', 'Pataudi Road', 'Dwark...","['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 St...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
1781,flat,experion windchants,sector 112,4.75,12622.0,3763.0,Super Built up area 3763(349.59 sq.m.),3,5,3+,servant room,4.0,West,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","['1 Water Purifier', '5 Geyser', '1 Chimney', ...","['Feng Shui / Vaastu Compliant', 'Security / F..."
1400,flat,avl 36 gurgaon,sector 36a,0.75,7500.0,1000.0,Super Built up area 1000(92.9 sq.m.)Carpet are...,2,2,2,not available,5.0,North-East,1 to 5 Year Old,"['S.R.S. Hospital and Critical Care Unit', 'Sh...","['1 Wardrobe', '3 Fan', '6 Light', '1 Modular ...","['Feng Shui / Vaastu Compliant', 'Intercom Fac..."

In [33]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [34]:
df.duplicated().sum()

np.int64(80)

In [35]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)